### ISSUE TITLE
为什么取消订阅要放在update里？

### ISSUE THREAD

**Issue by davidthompsons** [XuToWei/ET-DynamicEvent#2]
为什么移除组件不立即从registeredEntityDict移除对应的entity，而是先记录再在update里移除？
另外为什么这个update方法里在registeredEntityDict找到一个entity.GetType()就break跳出循环？
public void Update()
        {
            if (this.needRemoveEntities.Count < 1)
            {
                return;
            }
            foreach (Entity entity in this.needRemoveEntities)
            {
                if (this.registeredEntityDict.TryGetValue(entity.GetType(), out var entityRefs))
                {
                    entityRefs.Remove(entity);
                    break;
                }
            }
            this.needRemoveEntities.Clear();
        }

**Comment by XuToWei** [comment]
已修复，可能会出现在事件处理中取消事件的情况，所以放在了Update里删除，直接删除会导致迭代器中删除元素报错
